In [1]:
import sys

print(sys.executable)
print(sys.version)

c:\Users\Owner\anaconda3\envs\kaggle_env\python.exe
3.11.15 | packaged by Anaconda, Inc. | (main, Jun 11 2026, 15:12:53) [MSC v.1942 64 bit (AMD64)]

In [2]:
import numpy as np
import pandas as pd
import matplotlib
import sklearn

print("NumPy:", np.__version__)
print("pandas:", pd.__version__)
print("Matplotlib:", matplotlib.__version__)
print("scikit-learn:", sklearn.__version__)

NumPy: 2.4.6
pandas: 3.0.3
Matplotlib: 3.11.0
scikit-learn: 1.9.0

In [3]:
sample_data = pd.DataFrame(
    {
        "name":["A","B","C","D"],
        "Age":[20, 25, 30, 35],
        "score":[70, 85, 90, 75]
    }
)

sample_data

  name  Age  score
0    A   20     70
1    B   25     85
2    C   30     90
3    D   35     75

In [4]:
sample_data.describe()

             Age      score
count   4.000000   4.000000
mean   27.500000  80.000000
std     6.454972   9.128709
min    20.000000  70.000000
25%    23.750000  73.750000
50%    27.500000  80.000000
75%    31.250000  86.250000
max    35.000000  90.000000